import type { CSSProperties } from "react";

export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  filterInput: {
    width: "100%",
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    fontSize: 13,
    marginBottom: 8,
    outline: "none",
  } satisfies CSSProperties,
  statusLine: { minHeight: 20, fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  error: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13,
    color: "var(--crit)",
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  rowMain: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  path: { fontSize: 13, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
  /** Visible to assistive tech only: carries the FULL path while the screen shows an elided one. */
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  meta: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  reason: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  warn: { fontSize: 12, color: "var(--warn, var(--crit))" } satisfies CSSProperties,
  link: { fontSize: 12, color: "var(--accent)" } satisfies CSSProperties,
  linkBtn: { background: "none", border: 0, padding: 0, cursor: "pointer" } satisfies CSSProperties,
  iconBtn: {
    minWidth: 24,
    minHeight: 24,
    display: "inline-grid",
    placeItems: "center",
    padding: 0,
    borderRadius: 5,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  handle: { display: "inline-flex", color: "var(--text-muted)" } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  tokenWrap: { position: "relative", display: "inline-flex" } satisfies CSSProperties,
  token: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  tooltip: {
    position: "absolute",
    top: "100%",
    left: 0,
    zIndex: 10,
    marginTop: 4,
    padding: "6px 8px",
    width: 220,
    fontSize: 12,
    borderRadius: 6,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  meter: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: "8px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    fontSize: 13,
  } satisfies CSSProperties,
} as const;
