import type { CSSProperties } from "react";

export const s = {
  root: { maxWidth: 760, margin: "0 auto", padding: "24px 32px", display: "flex", flexDirection: "column", gap: 20 },
  h1: { fontSize: 22, fontWeight: 600, margin: 0 },
  subtitle: { margin: "4px 0 0", fontSize: 13, color: "var(--text-muted)" },
  step: { display: "flex", flexDirection: "column", gap: 10 },
  stepHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12 },
  stepHeading: { display: "flex", alignItems: "center", gap: 10, fontSize: 14, fontWeight: 600, margin: 0 },
  badge: {
    width: 22,
    height: 22,
    borderRadius: "50%",
    display: "grid",
    placeItems: "center",
    fontSize: 12,
    fontWeight: 600,
    color: "var(--accent-text)",
    background: "var(--accent-bg)",
    border: "1px solid var(--accent)",
  },
  selectAll: {
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    fontSize: 13,
    color: "var(--accent)",
  },
  select: {
    minHeight: 32,
    padding: "6px 10px",
    borderRadius: 6,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    fontSize: 14,
  },
  note: { fontSize: 13, color: "var(--text-muted)", margin: 0 },
  footer: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" },
  reason: { fontSize: 13, color: "var(--text-muted)" },
  error: { fontSize: 13, color: "var(--crit)", margin: 0 },
  link: { color: "var(--accent)", fontSize: 13 },
} satisfies Record<string, CSSProperties>;
