import type { CSSProperties } from "react";

/** Co-located styles for the Project Context page and its presentational children. */
export const s = {
  /** Same page gutter as the Conventions page; without it the content sits flush against the shell. */
  page: { maxWidth: 1240, margin: "0 auto", padding: "28px 28px 64px" } satisfies CSSProperties,
  pageHeader: { marginBottom: 16 } satisfies CSSProperties,
  pageTitle: { fontSize: 22, fontWeight: 650, margin: 0 } satisfies CSSProperties,
  pageSubtitle: { fontSize: 13, color: "var(--text-secondary)", margin: "4px 0 0" } satisfies CSSProperties,
  layout: {
    display: "grid",
    gridTemplateColumns: "minmax(320px, 2fr) minmax(0, 3fr)",
    gap: 16,
    alignItems: "start",
  } satisfies CSSProperties,
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    overflow: "hidden",
  } satisfies CSSProperties,
  previewCard: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    padding: 16,
    minHeight: 200,
    minWidth: 0,
  } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0 } satisfies CSSProperties,
  loadingStack: { display: "flex", flexDirection: "column", gap: 8, padding: 16 } satisfies CSSProperties,
  banner: (tone: "warn" | "error"): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "8px 14px",
    fontSize: 13,
    borderBottom: "1px solid var(--border)",
    background: tone === "error" ? "var(--crit-bg)" : "var(--bg-elevated)",
    color: tone === "error" ? "var(--crit)" : "var(--text-secondary)",
  }),
  note: {
    padding: "8px 14px",
    fontSize: 12,
    color: "var(--text-muted)",
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,

  // CatalogFilters
  filters: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 12,
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  filterInput: {
    width: "100%",
    minHeight: 32,
    padding: "6px 10px",
    borderRadius: 6,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    fontSize: 13,
  } satisfies CSSProperties,
  chipRow: { display: "flex", gap: 6, flexWrap: "wrap" } satisfies CSSProperties,
  chip: (active: boolean): CSSProperties => ({
    minHeight: 28,
    minWidth: 28,
    padding: "4px 12px",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 500,
    border: "1px solid " + (active ? "var(--accent)" : "var(--border)"),
    background: active ? "var(--accent-bg)" : "transparent",
    color: active ? "var(--accent-text)" : "var(--text-secondary)",
  }),

  // DocRow
  row: (selected: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 12px 0 0",
    borderBottom: "1px solid var(--border)",
    background: selected ? "var(--bg-hover)" : "transparent",
  }),
  rowButton: {
    flex: 1,
    minWidth: 0,
    minHeight: 40,
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    textAlign: "left",
    color: "var(--text-primary)",
    background: "transparent",
    border: "none",
    cursor: "pointer",
  } satisfies CSSProperties,
  rowPath: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  rowMeta: { fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,

  // TokenEstimate
  tokenWrap: { position: "relative", display: "inline-block" } satisfies CSSProperties,
  token: {
    fontSize: 12,
    color: "var(--text-secondary)",
    padding: "2px 4px",
    minHeight: 24,
    minWidth: 24,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  tooltip: {
    position: "absolute",
    right: 0,
    top: "100%",
    zIndex: 10,
    width: 240,
    padding: "6px 10px",
    borderRadius: 6,
    fontSize: 12,
    lineHeight: 1.4,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,

  // DocPreview
  previewHeader: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
    paddingBottom: 10,
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  previewPath: { fontSize: 14, fontWeight: 600, overflowWrap: "anywhere", flex: 1, minWidth: 0 } satisfies CSSProperties,
  previewMuted: { fontSize: 13, color: "var(--text-secondary)", margin: 0 } satisfies CSSProperties,
  previewActions: { display: "flex", gap: 8, marginTop: 12 } satisfies CSSProperties,
  previewBody: { fontSize: 14, overflowWrap: "anywhere" } satisfies CSSProperties,

  // CatalogFooter
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 8,
    padding: "8px 14px",
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
};
