/**
 * Export to CI — the pure bundle generator (no DB, no GitHub, no fs). Every
 * file path and every file content comes from here (AC-35); the only client
 * input that survives is the optional workflow replacement (AC-130).
 */
import { stringify } from 'yaml';
import {
  AgentManifest,
  CI_ACTION_PINS,
  CI_LIMITS,
  CI_PATHS,
  CiTrigger,
} from '@devdigest/shared';
import type { CiFile, CiSkillEntry, MemoryItem, RunnerBundleFile } from '@devdigest/shared';
import {
  AGENTS_DIR,
  CI_PR_TITLE,
  MEMORY_PATH,
  RESULT_ARTIFACT_PREFIX,
  RESULT_FILE_NAME,
  SKILLS_DIR,
  SLUG_RE,
} from './constants.js';
import { sha256Hex, slugify, uniqueSlugs } from './helpers.js';
import type { CiAgent, CiSkillSource, PostAs } from './types.js';

export interface BundleInput {
  agent: CiAgent;
  /** Enabled linked skills, in agent order. */
  skills: CiSkillSource[];
  /** Workspace memory for the target repo, newest first. */
  memory: MemoryItem[];
  postAs: PostAs;
  /** This agent's triggers (manifest). */
  triggers: CiTrigger[];
  /** Union of the triggers of every agent in the repo, including this one (AC-119). */
  workflowTriggers: CiTrigger[];
  /** Slugs of every agent installed in the repo, including this one (upload steps). */
  installedSlugs: string[];
  runnerFiles: RunnerBundleFile[];
  /** Optional replacement for the workflow file (already size-checked); `null` = generated. */
  workflowOverride: string | null;
}

export interface Bundle {
  files: CiFile[];
  agentSlug: string;
  /** Slug + sha256 of every generated skill file, in agent order. */
  skills: CiSkillEntry[];
  prTitle: string;
  prBody: string;
}

export function agentManifestPath(slug: string): string {
  return `${AGENTS_DIR}/${slug}.yaml`;
}

/** Skill file: `source:` front matter (AC-67), then the body. */
export function skillFileContents(skill: CiSkillSource): string {
  const body = skill.body.endsWith('\n') ? skill.body : `${skill.body}\n`;
  return `---\nsource: ${skill.source}\n---\n${body}`;
}

export function agentManifestYaml(
  agent: CiAgent,
  skillSlugs: string[],
  postAs: PostAs,
  triggers: CiTrigger[],
): string {
  const manifest: AgentManifest = {
    name: agent.name,
    agent_version: agent.version,
    provider: agent.provider,
    model: agent.model,
    system_prompt: agent.systemPrompt,
    skills: skillSlugs,
    strategy: agent.strategy,
    ci_fail_on: agent.ciFailOn,
    post_as: postAs,
    triggers,
  };
  return stringify(manifest, { lineWidth: 0 });
}

/** One `MemoryItem` per line, newest first, at most 200; a `null` confidence is written as 0. */
export function memoryJsonl(memory: MemoryItem[]): string {
  const lines = memory.slice(0, CI_LIMITS.MEMORY_ITEMS_MAX).map((m) =>
    JSON.stringify({
      content: m.content,
      scope: m.scope,
      kind: m.kind,
      confidence: Number.isFinite(m.confidence) ? m.confidence : 0,
      sources: m.sources,
    }),
  );
  return lines.length ? `${lines.join('\n')}\n` : '';
}

/**
 * The shared workflow. No `run:` line expands PR-controlled data (AC-103);
 * the only expressions are secrets and the PR *number* in the concurrency group.
 */
export function workflowYaml(workflowTriggers: CiTrigger[], installedSlugs: string[]): string {
  const slugs = [...new Set(installedSlugs)].sort();
  for (const slug of slugs) {
    if (!SLUG_RE.test(slug)) throw new Error(`unsafe agent slug in workflow: ${slug}`);
  }
  const { checkout, setupNode, uploadArtifact } = CI_ACTION_PINS;
  const uploads = slugs
    .map(
      (slug) => `      - name: Upload result (${slug})
        if: always()
        uses: actions/upload-artifact@${uploadArtifact.sha} # ${uploadArtifact.version}
        with:
          name: ${RESULT_ARTIFACT_PREFIX}${slug}
          path: ${CI_PATHS.RESULT_DIR}/${slug}/${RESULT_FILE_NAME}
          if-no-files-found: ignore
`,
    )
    .join('');
  return `# Generated by DevDigest. Re-export from the studio to update it.
name: DevDigest review

on:
  pull_request:
    types: [${workflowTriggers.join(', ')}]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: devdigest-\${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: ${CI_LIMITS.JOB_TIMEOUT_MIN}
    steps:
      - uses: actions/checkout@${checkout.sha} # ${checkout.version}
        with:
          persist-credentials: false
      - uses: actions/setup-node@${setupNode.sha} # ${setupNode.version}
        with:
          node-version: "24"
      - name: Run DevDigest agents
        run: node ${CI_PATHS.RUNNER_DIR}/index.js
        env:
          OPENROUTER_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
${uploads}      - name: Fail when an agent produced no result
        if: always()
        run: |
          missing=0
          for manifest in ${AGENTS_DIR}/*.yaml; do
            [ -e "$manifest" ] || continue
            slug="$(basename "$manifest" .yaml)"
            if [ ! -f "${CI_PATHS.RESULT_DIR}/$slug/${RESULT_FILE_NAME}" ]; then
              echo "No DevDigest result for agent: $slug"
              missing=1
            fi
          done
          exit $missing
`;
}

export function setupPrBody(repo: string, agentName: string): string {
  return `This PR adds a DevDigest review agent ("${agentName}") to \`${repo}\`. It was generated by DevDigest; every file is listed below.

## Files
- \`${CI_PATHS.WORKFLOW}\` — the shared workflow; it runs every agent under \`${AGENTS_DIR}/\`
- \`${AGENTS_DIR}/<agent>.yaml\` — the agent manifest
- \`${SKILLS_DIR}/<skill>.md\` — one file per skill
- \`${MEMORY_PATH}\` — workspace memory for this repository
- \`${CI_PATHS.RUNNER_DIR}/\` — the prebuilt runner (${CI_PATHS.RUNNER_FILES.join(', ')})

## Before merging
1. Add \`OPENROUTER_API_KEY\` to this repository's Actions secrets.
2. Merge this PR. Optionally make the DevDigest check required to block merges.

## Trust model
- Anyone who can push a branch to this repository can change the workflow and the runner, and can read \`OPENROUTER_API_KEY\`.
- Pull requests from forks are skipped; the key is never given to them.
- A PR can change the files under \`.devdigest/\` (prompt, model, \`ci_fail_on\`, post mode, triggers, skills, memory), and that PR's own CI run uses the changed files.
- PR content (diff, title, body, branch names) reaches the model only as untrusted data.
`;
}

export function buildBundle(input: BundleInput, repo: string): Bundle {
  const agentSlug = slugify(input.agent.name);
  const skillSlugs = uniqueSlugs(input.skills.map((s) => s.name));

  const skillFiles = input.skills.map((skill, i) => ({
    path: `${SKILLS_DIR}/${skillSlugs[i]!}.md`,
    contents: skillFileContents(skill),
    slug: skillSlugs[i]!,
  }));

  const manifestYaml = agentManifestYaml(input.agent, skillSlugs, input.postAs, input.triggers);

  const workflowContents =
    input.workflowOverride ?? workflowYaml(input.workflowTriggers, input.installedSlugs);

  const files: CiFile[] = [
    { path: agentManifestPath(agentSlug), contents: manifestYaml, editable: false },
    ...skillFiles.map((f) => ({ path: f.path, contents: f.contents, editable: false })),
    { path: MEMORY_PATH, contents: memoryJsonl(input.memory), editable: false },
    ...input.runnerFiles.map((f) => ({
      path: `${CI_PATHS.RUNNER_DIR}/${f.name}`,
      contents: f.contents,
      editable: false,
    })),
    { path: CI_PATHS.WORKFLOW, contents: workflowContents, editable: true },
  ];

  return {
    files,
    agentSlug,
    skills: skillFiles.map((f) => ({ slug: f.slug, sha256: sha256Hex(f.contents) })),
    prTitle: CI_PR_TITLE,
    prBody: setupPrBody(repo, input.agent.name),
  };
}
