import type { CSSProperties } from "react";

export const s = {
  layout: { display: "grid", gridTemplateColumns: "250px 1fr", gap: 14, minHeight: 320 } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 4, minWidth: 0 } satisfies CSSProperties,
  file: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 2,
    width: "100%",
    padding: "7px 9px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "transparent",
    cursor: "pointer",
    textAlign: "left",
    minWidth: 0,
  } satisfies CSSProperties,
  fileOn: { background: "var(--bg-hover)", borderColor: "var(--border-strong)" } satisfies CSSProperties,
  path: { fontSize: 11.5, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", maxWidth: "100%" } satisfies CSSProperties,
  tag: { fontSize: 10.5, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.04em" } satisfies CSSProperties,
  viewer: { minWidth: 0, display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  editor: {
    flex: 1,
    minHeight: 300,
    padding: 10,
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    resize: "vertical",
  } satisfies CSSProperties,
  readOnly: {
    flex: 1,
    minHeight: 300,
    maxHeight: 420,
    overflow: "auto",
    margin: 0,
    padding: 10,
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
  } satisfies CSSProperties,
} as const;
