import type { CSSProperties } from "react";

export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 16, maxWidth: 900 } satisfies CSSProperties,
  title: { fontSize: 14, fontWeight: 600, margin: 0 } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-muted)", margin: 0 } satisfies CSSProperties,
  repoRow: { display: "flex", alignItems: "center", gap: 10, fontSize: 13 } satisfies CSSProperties,
  select: {
    padding: "6px 10px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    fontSize: 13,
  } satisfies CSSProperties,
  state: {
    border: "1px solid var(--border)",
    borderRadius: 9,
    background: "var(--bg-elevated)",
    padding: 16,
    fontSize: 13,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  stateTitle: { fontWeight: 600 } satisfies CSSProperties,
  stateBody: { color: "var(--text-muted)" } satisfies CSSProperties,
  link: { fontSize: 12, color: "var(--accent)", alignSelf: "flex-start" } satisfies CSSProperties,
  serialized: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  serializedHead: { display: "flex", justifyContent: "space-between", fontSize: 12.5, fontWeight: 600 } satisfies CSSProperties,
  pre: {
    margin: 0,
    padding: 12,
    maxHeight: 320,
    overflow: "auto",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    fontSize: 12,
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
