/**
 * T1 — the pure CI bundle generator (S2.1): manifest, skills, memory, workflow, PR body.
 */
import { describe, it, expect } from 'vitest';
import { parse } from 'yaml';
import { AgentManifest, CI_ACTION_PINS, CI_PATHS } from '@devdigest/shared';
import type { MemoryItem } from '@devdigest/shared';
import {
  buildBundle,
  memoryJsonl,
  skillFileContents,
  workflowYaml,
  type BundleInput,
} from '../src/modules/ci/bundle.js';
import { gitBlobSha, sha256Hex, slugify, uniqueSlugs } from '../src/modules/ci/helpers.js';
import type { CiAgent } from '../src/modules/ci/types.js';

const agent: CiAgent = {
  id: 'a1',
  name: 'Security Reviewer',
  version: 4,
  provider: 'openrouter',
  model: 'anthropic/claude-sonnet-4',
  systemPrompt: 'Review for security.\nBe terse: "quote" and colon: ok.',
  strategy: 'auto',
  ciFailOn: 'warning',
};

function input(over: Partial<BundleInput> = {}): BundleInput {
  return {
    agent,
    skills: [],
    memory: [],
    postAs: 'github_review',
    triggers: ['opened', 'synchronize', 'reopened'],
    workflowTriggers: ['opened', 'synchronize', 'reopened'],
    installedSlugs: ['security-reviewer'],
    runnerFiles: [
      { name: 'index.js', contents: '// index\n' },
      { name: '300.index.js', contents: '// chunk\n' },
      { name: 'package.json', contents: '{"type":"module"}\n' },
    ],
    workflowOverride: null,
    ...over,
  };
}

const mem = (over: Partial<MemoryItem> = {}): MemoryItem => ({
  content: 'Use zod',
  scope: 'global',
  kind: 'convention',
  confidence: 0.8,
  sources: [{ context: 'pr' }],
  ...over,
});

function fileOf(bundle: ReturnType<typeof buildBundle>, path: string) {
  const f = bundle.files.find((x) => x.path === path);
  if (!f) throw new Error(`missing ${path}`);
  return f;
}

describe('slug helpers', () => {
  it('slugifies to a path-safe name and never returns empty', () => {
    expect(slugify('Security Reviewer!')).toBe('security-reviewer');
    expect(slugify('../../etc/passwd')).toBe('etc-passwd');
    expect(slugify('!!!')).toBe('agent');
  });

  it('suffixes repeated skill slugs with -2, -3', () => {
    expect(uniqueSlugs(['Lint', 'lint', 'LINT', 'Other'])).toEqual(['lint', 'lint-2', 'lint-3', 'other']);
  });

  it('computes the git blob sha GitHub reports', () => {
    // `printf 'hello\n' | git hash-object --stdin`
    expect(gitBlobSha('hello\n')).toBe('ce013625030ba8dba906f756967f9e9ca394464a');
  });
});

describe('bundle files (AC-146, AC-184)', () => {
  it('lists manifest, skills, memory, both runner files and the workflow, in that order', () => {
    const b = buildBundle(
      input({
        skills: [
          { name: 'Auth rules', source: 'manual', body: 'a' },
          { name: 'SQL rules', source: 'imported_url', body: 'b' },
        ],
      }),
      'acme/api',
    );
    expect(b.files.map((f) => f.path)).toEqual([
      '.devdigest/agents/security-reviewer.yaml',
      '.devdigest/skills/auth-rules.md',
      '.devdigest/skills/sql-rules.md',
      '.devdigest/memory.jsonl',
      '.devdigest/runner/index.js',
      '.devdigest/runner/300.index.js',
      '.devdigest/runner/package.json',
      '.github/workflows/devdigest-review.yml',
    ]);
    expect(b.files.filter((f) => f.editable).map((f) => f.path)).toEqual([CI_PATHS.WORKFLOW]);
  });

  it('has no skill file when the agent has no enabled skill (EC-16)', () => {
    const b = buildBundle(input(), 'acme/api');
    expect(b.files.some((f) => f.path.startsWith('.devdigest/skills/'))).toBe(false);
    expect(b.skills).toEqual([]);
    expect(fileOf(b, '.devdigest/memory.jsonl').contents).toBe('');
  });

  it('dedupes skill slugs and records the sha256 of the generated bytes', () => {
    const b = buildBundle(
      input({
        skills: [
          { name: 'Lint', source: 'manual', body: 'one' },
          { name: 'lint', source: 'extracted', body: 'two' },
        ],
      }),
      'acme/api',
    );
    expect(b.skills.map((s) => s.slug)).toEqual(['lint', 'lint-2']);
    const f = fileOf(b, '.devdigest/skills/lint-2.md');
    expect(b.skills[1]!.sha256).toBe(sha256Hex(f.contents));
    expect(f.contents).toBe('---\nsource: extracted\n---\ntwo\n');
  });

  it('writes the source front matter before the body', () => {
    expect(skillFileContents({ name: 'x', source: 'manual', body: 'body\n' })).toBe(
      '---\nsource: manual\n---\nbody\n',
    );
  });
});

describe('agent manifest (AC-38, AC-131)', () => {
  it('round-trips through AgentManifest', () => {
    const b = buildBundle(
      input({
        skills: [{ name: 'Auth rules', source: 'manual', body: 'a' }],
        postAs: 'pr_comment',
        triggers: ['opened'],
      }),
      'acme/api',
    );
    const parsed = AgentManifest.parse(parse(fileOf(b, '.devdigest/agents/security-reviewer.yaml').contents));
    expect(parsed).toEqual({
      name: 'Security Reviewer',
      agent_version: 4,
      provider: 'openrouter',
      model: 'anthropic/claude-sonnet-4',
      system_prompt: agent.systemPrompt,
      skills: ['auth-rules'],
      strategy: 'auto',
      ci_fail_on: 'warning',
      post_as: 'pr_comment',
      triggers: ['opened'],
    });
  });
});

describe('memory.jsonl (AC-40)', () => {
  it('writes one MemoryItem per line, null confidence as 0, at most 200', () => {
    const items = Array.from({ length: 205 }, (_, i) => mem({ content: `m${i}` }));
    items[0] = mem({ content: 'first', confidence: null as unknown as number });
    const lines = memoryJsonl(items).trimEnd().split('\n');
    expect(lines).toHaveLength(200);
    expect(JSON.parse(lines[0]!)).toMatchObject({ content: 'first', confidence: 0 });
    expect(JSON.parse(lines[199]!).content).toBe('m199');
  });
});

describe('workflow (AC-42–49, AC-103, AC-132)', () => {
  const wf = workflowYaml(['opened', 'synchronize'], ['security-reviewer', 'perf']);
  const doc = parse(wf) as {
    on: Record<string, { types: string[] }>;
    permissions: Record<string, string>;
    concurrency: { group: string; 'cancel-in-progress': boolean };
    jobs: { review: { 'timeout-minutes': number; steps: Record<string, unknown>[] } };
  };

  it('triggers only on pull_request with the given union, never pull_request_target', () => {
    expect(Object.keys(doc.on)).toEqual(['pull_request']);
    expect(doc.on.pull_request!.types).toEqual(['opened', 'synchronize']);
    expect(wf).not.toContain('pull_request_target');
  });

  it('declares exactly the two permissions', () => {
    expect(doc.permissions).toEqual({ contents: 'read', 'pull-requests': 'write' });
  });

  it('has a per-PR concurrency group with cancel-in-progress and a 10 minute timeout', () => {
    expect(doc.concurrency).toEqual({
      group: 'devdigest-${{ github.event.pull_request.number }}',
      'cancel-in-progress': true,
    });
    expect(doc.jobs.review['timeout-minutes']).toBe(10);
  });

  it('pins every action by full SHA with the version as a trailing comment', () => {
    const uses = wf.split('\n').filter((l) => l.includes('uses:'));
    expect(uses.length).toBeGreaterThanOrEqual(4);
    for (const l of uses) expect(l).toMatch(/uses: [\w-]+\/[\w-]+@[0-9a-f]{40} # v\d+\.\d+\.\d+$/);
    expect(wf).toContain(`actions/checkout@${CI_ACTION_PINS.checkout.sha} # ${CI_ACTION_PINS.checkout.version}`);
    expect(wf).toContain(`actions/setup-node@${CI_ACTION_PINS.setupNode.sha} # ${CI_ACTION_PINS.setupNode.version}`);
    expect(wf).toContain(
      `actions/upload-artifact@${CI_ACTION_PINS.uploadArtifact.sha} # ${CI_ACTION_PINS.uploadArtifact.version}`,
    );
  });

  it('sets up Node 24 and starts the runner as node .devdigest/runner/index.js', () => {
    expect(wf).toContain('node-version: "24"');
    expect(wf).toContain('run: node .devdigest/runner/index.js');
  });

  it('passes the key to the runner step only from secrets', () => {
    const steps = doc.jobs.review.steps as { env?: Record<string, string>; run?: string }[];
    const runner = steps.find((s) => s.run === 'node .devdigest/runner/index.js')!;
    expect(runner.env!.OPENROUTER_API_KEY).toBe('${{ secrets.OPENROUTER_API_KEY }}');
    expect(wf.match(/secrets\.OPENROUTER_API_KEY/g)).toHaveLength(1);
    expect(wf.match(/secrets\.\w+/g)!.sort()).toEqual(['secrets.GITHUB_TOKEN', 'secrets.OPENROUTER_API_KEY']);
  });

  it('uploads one always() artifact per installed agent slug', () => {
    const uploads = (doc.jobs.review.steps as { uses?: string; if?: string; with?: Record<string, string> }[]).filter(
      (s) => s.uses?.startsWith('actions/upload-artifact@'),
    );
    expect(uploads.map((u) => u.with!.name)).toEqual(['devdigest-result-perf', 'devdigest-result-security-reviewer']);
    for (const u of uploads) expect(u.if).toBe('always()');
    expect(uploads[1]!.with!.path).toBe('.devdigest-results/security-reviewer/devdigest-result.json');
  });

  it('ends with an always() step that fails when a manifest has no result file', () => {
    const steps = doc.jobs.review.steps as { if?: string; run?: string }[];
    const last = steps[steps.length - 1]!;
    expect(last.if).toBe('always()');
    expect(last.run).toContain('.devdigest/agents/*.yaml');
    expect(last.run).toContain('.devdigest-results/$slug/devdigest-result.json');
    expect(last.run).toContain('exit $missing');
  });

  it('expands no PR-controlled data in any run: line', () => {
    const steps = doc.jobs.review.steps as { run?: string }[];
    for (const s of steps) if (s.run) expect(s.run).not.toContain('${{');
    expect(wf).not.toMatch(/github\.event\.pull_request\.(title|body|head)/);
    expect(wf).not.toContain('github.head_ref');
  });

  it('refuses an unsafe slug', () => {
    expect(() => workflowYaml(['opened'], ['x"; rm -rf /'])).toThrow();
  });
});

describe('buildBundle options', () => {
  it('uses the workflow override verbatim and keeps every other file generated (AC-130)', () => {
    const b = buildBundle(input({ workflowOverride: 'name: mine\n' }), 'acme/api');
    expect(fileOf(b, CI_PATHS.WORKFLOW).contents).toBe('name: mine\n');
    expect(fileOf(b, '.devdigest/runner/index.js').contents).toBe('// index\n');
  });

  it('carries no secret and states the trust model in the PR body (AC-50, AC-51, AC-167)', () => {
    const b = buildBundle(input(), 'acme/api');
    expect(b.prTitle).toBe('Add DevDigest CI review');
    expect(b.prBody).toContain('push a branch');
    expect(b.prBody).toContain('OPENROUTER_API_KEY');
    expect(b.prBody).toMatch(/forks? .*skipped/i);
    expect(b.prBody).toContain('.devdigest/');
    expect(b.prBody).toContain("that PR's own CI run uses the changed files");
    for (const f of b.files) expect(f.contents).not.toMatch(/sk-or-|ghp_|github_pat_/);
  });
});
