import type { CSSProperties } from "react";

export const s = {
  root: { display: "flex", flexDirection: "column", gap: 4 },
  head: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "2px 8px" },
  heading: { fontSize: 11, fontWeight: 600, letterSpacing: ".04em", color: "var(--text-muted)" },
  clear: {
    minHeight: 24,
    minWidth: 24,
    padding: "0 6px",
    background: "transparent",
    border: "none",
    borderRadius: 4,
    color: "var(--accent)",
    fontSize: 12,
    cursor: "pointer",
  },
  row: { display: "flex", alignItems: "center", gap: 6, padding: "0 4px 0 8px", minHeight: 28 },
  name: { display: "flex", alignItems: "center", gap: 6, minWidth: 0 },
  grow: { flex: 1, minWidth: 0 },
  tag: { fontSize: 11, color: "var(--text-muted)", flexShrink: 0 },
  estimate: { fontSize: 11.5, color: "var(--text-muted)", flexShrink: 0 },
  runBtn: {
    display: "grid",
    placeItems: "center",
    minWidth: 24,
    minHeight: 24,
    padding: 0,
    background: "transparent",
    border: "none",
    borderRadius: 4,
    color: "var(--text-muted)",
    cursor: "pointer",
    flexShrink: 0,
  },
  actions: { display: "flex", flexDirection: "column", gap: 4, padding: "4px 8px" },
  hint: { fontSize: 12, color: "var(--text-muted)", margin: 0 },
  error: { fontSize: 12, color: "var(--crit)", margin: 0 },
  link: { color: "var(--accent)", fontSize: 12.5, minHeight: 24, display: "inline-flex", alignItems: "center" },
  footer: { display: "flex", alignItems: "center", gap: 8, padding: "5px 8px", fontSize: 13, color: "var(--text-muted)", minHeight: 28 },
} satisfies Record<string, CSSProperties>;
